safe: true
encoding: UTF-8
url: https://roundcube.net
enforce_ssl: roundcube.net
hostname: "https://roundcube.net"
permalink: news/:year/:month/:day/:title
exclude: [vendor]
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "/news/page:num/"
environment: "production"
num_related_items: 5
libs: {
    fonts: {
        roboto: 'https://fonts.googleapis.com/css?family=Roboto&amp;display=swap',
        fontawesome: 'https://kit.fontawesome.com/4cdeb7a6e0.js'
    },
    less: {
        url: 'https://cdn.jsdelivr.net/npm/less@4.1.1/dist/less.min.js',
        sri: 'sha256-CYttzE5ypefNk7d3bCMASKNanIMq21aAUBEtlUfJ7C8='
    },
    css: '/styles/styles.min.css?v=2021123000',
    bootstrap: {
        css: {
            url: 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css',
            sri: 'sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3'
        },
        js: {
            url: 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js',
            sri: 'sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13'
        }
    }
}
